[repo]
logging = "warn"

[repo_docs]
enabled = true
social_media_set = []
social_media = []
favicon = "${root}/assets/favicon.ico"
logo = "${root}/assets/nvidia-logo-white.png"

sphinx_conf_py_extra = """
  templates_path = ['${root}/templates']
  extensions.extend(["sphinx.ext.autosectionlabel", "sphinx_copybutton", "sphinx_tabs.tabs", "sphinxcontrib.blockdiag"])
  suppress_warnings = [ 'autosectionlabel.*' ]
  blockdiag_fontpath = '/usr/share/fonts/truetype/Roboto-Regular.ttf'
  blockdiag_antialias = True
  pygments_style = 'sphinx'
  html_theme_options = {
    'titles_only': True,
    'logo_only': True,
  }
  html_domain_indices = False
  html_use_index = False
  html_extra_path = ["versions.json"]
  html_static_path.append("${root}/css/")
  html_css_files.append("custom.css")
  highlight_language = 'console'
  rst_epilog = ".. |gitlab_mr_url| replace:: Sorry Charlie...not a merge request."
  if os.environ.get("CI_MERGE_REQUEST_IID") is not None:
    rst_epilog = ".. |gitlab_mr_url| replace:: {}/-/merge_requests/{}".format(
      os.environ["CI_MERGE_REQUEST_PROJECT_URL"], os.environ["CI_MERGE_REQUEST_IID"])
"""

#deps = [
#  ["container-toolkit", "_build/docs/container-toolkit/latest"],
#  ["driver-containers", "_build/docs/driver-containers/latest"],
#  ["gpu-operator", "_build/docs/gpu-operator/latest"]
#]


[repo_docs.projects.container-toolkit]
docs_root = "${root}/container-toolkit"
project = "container-toolkit"
name = "NVIDIA Container Toolkit"
version = "1.13.1"
copyright_start = 2020


[repo_docs.projects.driver-containers]
docs_root = "${root}/driver-containers"
project = "driver-containers"
name = "NVIDIA Driver Containers"
version = "1.0"
copyright_start = 2020


[repo_docs.projects.gpu-operator]
docs_root = "${root}/gpu-operator"
project = "gpu-operator"
name = "NVIDIA GPU Operator"
version = "23.0.0"
copyright_start = 2020

[repo_docs.projects.review]
docs_root = "${root}/review"
name = "Technical Review"
version = "0.1.0"
copyright_start = 2023